### PR TITLE
Switch from Jinja2 to Genshi

### PR DESCRIPTION
**Pull request by dennisroberts71**

### CODE REVIEW

**Comment by psarando** [comment]
Looks good to me! :shipit:

**Comment by dennisroberts71** [comment]
Cool, thanks for the review.

**Comment by upendrak** [comment]
Yes it looks good to me too..Thanks Dennis for getting started on this. Can't wait to see the WGS app!!!

**Comment by dennisroberts71** [comment]
Cool. Thanks for looking it over.

**Comment by psarando** [comment]
I didn't catch this before the merge, but now that we're using Genshi instead of Jinja2, we can probably get rid of the XML escaping in [metadata_client.py](https://github.com/iPlantCollaborativeOpenSource/docker-builds/blob/49cce38ae9167df55b9b5e5b3e60598e269bbf48/ncbi-sra-submit/metadata_client.py#L4).

**Comment by dennisroberts71** [comment]
Ah, thanks for catching that. I'll get rid of that next.

**Pull request merged**
