### PR TITLE
Upgrade NCBI submit tools with Aspera Connect v4

### PR DESCRIPTION
**Pull request by psarando**
Upgrades the NCBI SRA and WGS submission tools with the latest version of [Aspera Connect](https://www.ibm.com/aspera/connect/), which now requires installation as a user other than the `root` user.

CORE-1907

### CODE REVIEW

**Review by slr71 — APPROVED** [review]
Looks good to me! :shipit:

**Review by johnworth — APPROVED** [review]
LGTM

**Comment by slr71** [comment]
Looks good to me! :shipit:

**Comment by psarando** [comment]
Thanks for the reviews! 👍

**Pull request merged**
